#!/bin/bash
# TCP vs UDS 技术差异分析

echo "=== TCP vs UDS 技术差异分析 ==="
echo ""
echo "1. 协议栈层面差异"
echo "   TCP:"
echo "     - 需要完整的网络协议栈处理"
echo "     - 应用层 → 传输层(TCP) → 网络层(IP) → 数据链路层 → 物理层"
echo "     - 需要处理TCP头部(20字节) + IP头部(20字节)"
echo "     - 需要进行校验和计算、序列号处理、确认机制"
echo ""
echo "   UDS:"
echo "     - 直接在内核中进行进程间通信"
echo "     - 不需要网络协议栈处理"
echo "     - 只需要文件系统路径作为地址"
echo "     - 数据直接在内核缓冲区之间拷贝"
echo ""

echo "2. 数据传输路径"
echo "   TCP:"
echo "     - 数据需要经过多次拷贝："
echo "       用户空间 → 内核TCP缓冲区 → 内核IP缓冲区 → 网络设备"
echo "     - 需要进行网络包的封装和解封装"
echo "     - 需要路由查找、ARP解析等网络操作"
echo ""
echo "   UDS:"
echo "     - 数据拷贝路径更短："
echo "       用户空间 → 内核UDS缓冲区 → 目标进程"
echo "     - 不需要网络包封装"
echo "     - 直接通过文件系统路径寻址"
echo ""

echo "3. 系统调用开销"
echo "   TCP:"
echo "     - send()/recv() 需要处理网络协议"
echo "     - 需要进行网络状态检查"
echo "     - 需要处理拥塞控制、流量控制"
echo ""
echo "   UDS:"
echo "     - send()/recv() 直接在内核中传递数据"
echo "     - 不需要网络状态检查"
echo "     - 不需要拥塞控制"
echo ""

echo "4. 上下文切换"
echo "   TCP:"
echo "     - 需要更多的内核处理路径"
echo "     - 网络中断处理"
echo "     - 软中断处理(NET_RX_SOFTIRQ)"
echo ""
echo "   UDS:"
echo "     - 更少的内核处理路径"
echo "     - 不需要网络中断"
echo "     - 直接的进程唤醒机制"
echo ""

echo "5. 性能优势对比"
echo "   根据测试结果："
echo "   - QPS提升：2%-8%"
echo "   - 延迟降低：2%-8%"
echo "   - 高并发下优势更明显"
echo "   - 延迟波动更小（标准差更低）"
echo ""

echo "6. 适用场景"
echo "   TCP适用场景："
echo "     - 跨机器通信"
echo "     - 需要网络传输的场景"
echo "     - 需要防火墙、负载均衡等网络功能"
echo ""
echo "   UDS适用场景："
echo "     - 本地进程间通信"
echo "     - 微服务网关与后端服务通信"
echo "     - 数据库代理"
echo "     - 高性能IPC场景"
echo ""

echo "7. 实现复杂度"
echo "   TCP:"
echo "     - 需要处理网络异常"
echo "     - 需要处理连接断开、重连"
echo "     - 需要考虑网络安全"
echo ""
echo "   UDS:"
echo "     - 实现简单"
echo "     - 不需要处理网络异常"
echo "     - 通过文件系统权限控制访问"
echo ""

echo "=== 结论 ==="
echo "UDS在本地进程间通信场景下明显优于TCP："
echo "1. 性能更好：QPS更高，延迟更低"
echo "2. 资源消耗更少：不需要网络协议栈处理"
echo "3. 实现更简单：不需要处理网络复杂性"
echo "4. 更安全：通过文件系统权限控制访问"
echo ""
echo "推荐：在微服务架构中，网关与后端服务如果部署在同一台机器上，"
echo "应该优先使用UDS进行通信，以获得更好的性能。"
